name: star
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flare_flutter:
  # crypto:
  #屏幕适配
  flutter_screenutil:
  #状态通知
  provide:
  #路由管理
  fluro:
  #请求loading
  flui:
  #dialog弹框
  fluttertoast:
  #网络图片加载
  cached_network_image:
  #网络请求
  dio:
  #状态共享
  shared_preferences:
  #json_serializable:
  #單圖選擇
  image_picker:
  #圖片裁剪
  image_cropper:
  #package_info:
  #验证码框
  pin_code_fields:
  #仿iOS的底部弹出datapicker
  flutter_picker:
  #轮播
  flutter_swiper:
  #flutter_webview_plugin:
  #上傳進度
  progress_dialog: ^1.2.2
  #動畫效果
  sa_anicoto:
  #一些工具類方法比如 toInt toColor
  supercharged: ^1.6.0
  audioplayers:
  flutter_radio_slider:
  web_socket_channel:
  chat_bubble:
  auto_size_text:
  dotted_decoration: ^1.2.2

  flutter_app_upgrade: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
  - assets/sounds/
  - assets/images/mine/
  - assets/images/game/
  - assets/images/
  - assets/images/pokes/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: pf
      fonts:
        - asset: assets/font/PingFang_Regular.ttf
          weight: 400
        - asset: assets/font/PingFang_Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
